image: node:latest
before_script:
  - apt-get update -qq && apt-get install
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
stages:
  - install
  - test
  - package
  - deploy
cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - yarn install

test:
  stage: test
  script:
    - yarn test

package:dev:
  stage: package
  script:
    - yarn package:dev
    
package:prod:
  stage: package
  script:
    - yarn package:prod

deploy:dev:
  stage: deploy
  script:
    - yarn deploy:dev
  dependencies:
    - install
  when: manual

deploy:prod:
  stage: deploy
  script:
    - yarn deploy:dev
  dependencies:
    - install
  only:
    refs:
      - master
