image: node:latest
before_script:
  - apt-get update -qq && apt-get install
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
stages:
  - install
  - test
  - package
  - deploy
cache:
  paths:
    - node_modules/
install:
  stage: install
  script:
    - yarn install
test:
  stage: test
  script:
    - yarn test
package:
  stage: package
  script:
    - yarn package
deploy:
  stage: deploy
  script:
    - yarn deploy
  dependencies:
    - install
  when: manual
