service:
  name: email-parser

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-2

functions:
  app:
    handler: handler.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
    timeout: 900
