service:
  name: email-parser

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2

functions:
  parse:
    handler: handler.parse
    events:
      - http:
          path: parse
          method: post
          cors: true
    timeout: 900
